<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\TokenUsage;

use Atlas\Table\Table;

/**
 * @method TokenUsageRow|null fetchRow($primaryVal)
 * @method TokenUsageRow[] fetchRows(array $primaryVals)
 * @method TokenUsageTableSelect select(array $whereEquals = [])
 * @method TokenUsageRow newRow(array $cols = [])
 * @method TokenUsageRow newSelectedRow(array $cols)
 */
class TokenUsageTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'token_usage';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'token_id' => [
            'name' => 'token_id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'request_uri' => [
            'name' => 'request_uri',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'date_time_of_request' => [
            'name' => 'date_time_of_request',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => '0000-00-00 00:00:00',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'request_full_details' => [
            'name' => 'request_full_details',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'requesters_ip' => [
            'name' => 'requesters_ip',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => 'NOIP',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'http_status_code' => [
            'name' => 'http_status_code',
            'type' => 'VARCHAR',
            'size' => 3,
            'scale' => null,
            'notnull' => true,
            'default' => '200',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'request_error_details' => [
            'name' => 'request_error_details',
            'type' => 'TEXT',
            'size' => null,
            'scale' => null,
            'notnull' => false,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'token_id',
        'request_uri',
        'date_time_of_request',
        'request_full_details',
        'requesters_ip',
        'http_status_code',
        'request_error_details',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'token_id' => null,
        'request_uri' => null,
        'date_time_of_request' => '0000-00-00 00:00:00',
        'request_full_details' => null,
        'requesters_ip' => 'NOIP',
        'http_status_code' => '200',
        'request_error_details' => null,
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
