<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\TokenUsage;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $token_id INTEGER NOT NULL
 * @property mixed $request_uri VARCHAR(255) NOT NULL
 * @property mixed $date_time_of_request VARCHAR(255) NOT NULL
 * @property mixed $request_full_details TEXT NOT NULL
 * @property mixed $requesters_ip VARCHAR(255) NOT NULL
 * @property mixed $http_status_code VARCHAR(3) NOT NULL
 * @property mixed $request_error_details TEXT
 */
class TokenUsageRow extends Row
{
    protected $cols = [
        'id' => null,
        'token_id' => null,
        'request_uri' => null,
        'date_time_of_request' => '0000-00-00 00:00:00',
        'request_full_details' => null,
        'requesters_ip' => 'NOIP',
        'http_status_code' => '200',
        'request_error_details' => null,
    ];
}
