<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\TokenUsage;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $token_id INTEGER NOT NULL
 * @property mixed $request_uri VARCHAR(255) NOT NULL
 * @property mixed $date_time_of_request VARCHAR(255) NOT NULL
 * @property mixed $request_full_details TEXT NOT NULL
 * @property mixed $requesters_ip VARCHAR(255) NOT NULL
 * @property null|false|\Lsia\Atlas\Models\Token\TokenRecord $token
 */
trait TokenUsageFields
{
}
