<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\Token;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $generators_username VARCHAR(255) NOT NULL
 * @property mixed $token VARCHAR(255) NOT NULL
 * @property mixed $date_created VARCHAR(255) NOT NULL
 * @property mixed $max_requests_per_day BIGINTEGER NOT NULL
 * @property mixed $expiry_date VARCHAR(255) NOT NULL
 * @property mixed $creators_ip VARCHAR(255) NOT NULL
 */
trait TokenFields
{
}
