<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\Token;

use Atlas\Table\Table;

/**
 * @method TokenRow|null fetchRow($primaryVal)
 * @method TokenRow[] fetchRows(array $primaryVals)
 * @method TokenTableSelect select(array $whereEquals = [])
 * @method TokenRow newRow(array $cols = [])
 * @method TokenRow newSelectedRow(array $cols)
 */
class TokenTable extends Table
{
    const DRIVER = 'sqlite';

    const NAME = 'tokens';

    const COLUMNS = [
        'id' => [
            'name' => 'id',
            'type' => 'INTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => true,
            'primary' => true,
            'options' => null,
        ],
        'generators_username' => [
            'name' => 'generators_username',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'token' => [
            'name' => 'token',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => null,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'date_created' => [
            'name' => 'date_created',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => '0000-00-00 00:00:00',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'max_requests_per_day' => [
            'name' => 'max_requests_per_day',
            'type' => 'BIGINTEGER',
            'size' => null,
            'scale' => null,
            'notnull' => true,
            'default' => 0,
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'expiry_date' => [
            'name' => 'expiry_date',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => '0000-00-00 00:00:00',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
        'creators_ip' => [
            'name' => 'creators_ip',
            'type' => 'VARCHAR',
            'size' => 255,
            'scale' => null,
            'notnull' => true,
            'default' => 'NOIP',
            'autoinc' => false,
            'primary' => false,
            'options' => null,
        ],
    ];

    const COLUMN_NAMES = [
        'id',
        'generators_username',
        'token',
        'date_created',
        'max_requests_per_day',
        'expiry_date',
        'creators_ip',
    ];

    const COLUMN_DEFAULTS = [
        'id' => null,
        'generators_username' => null,
        'token' => null,
        'date_created' => '0000-00-00 00:00:00',
        'max_requests_per_day' => 0,
        'expiry_date' => '0000-00-00 00:00:00',
        'creators_ip' => 'NOIP',
    ];

    const PRIMARY_KEY = [
        'id',
    ];

    const AUTOINC_COLUMN = 'id';

    const AUTOINC_SEQUENCE = null;
}
