<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\Token;

use Atlas\Table\Row;

/**
 * @property mixed $id INTEGER NOT NULL
 * @property mixed $generators_username VARCHAR(255) NOT NULL
 * @property mixed $token VARCHAR(255) NOT NULL
 * @property mixed $date_created VARCHAR(255) NOT NULL
 * @property mixed $max_requests_per_day BIGINTEGER NOT NULL
 * @property mixed $expiry_date VARCHAR(255) NOT NULL
 * @property mixed $creators_ip VARCHAR(255) NOT NULL
 */
class TokenRow extends Row
{
    protected $cols = [
        'id' => null,
        'generators_username' => null,
        'token' => null,
        'date_created' => '0000-00-00 00:00:00',
        'max_requests_per_day' => 0,
        'expiry_date' => '0000-00-00 00:00:00',
        'creators_ip' => 'NOIP',
    ];
}
