<?php
/**
 * This file was generated by Atlas. Changes will be overwritten.
 */
declare(strict_types=1);

namespace Lsia\Atlas\Models\Phinxlog;

/**
 * @property mixed $version BIGINTEGER NOT NULL
 * @property mixed $migration_name VARCHAR(100)
 * @property mixed $start_time TIMESTAMP_TEXT
 * @property mixed $end_time TIMESTAMP_TEXT
 * @property mixed $breakpoint BOOLEAN_INTEGER NOT NULL
 */
trait PhinxlogFields
{
}
